version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.grinVersion={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - src: LICENSE
      - src: README.md
      - src: doc/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - repository:
      owner: Yoshi325
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/Yoshi325/grin"
    description: "Make INI files greppable"
    license: "MIT"
    install: |
      bin.install "grin"
      man1.install "doc/grin.1"
    test: |
      assert_match "grin version", shell_output("#{bin}/grin --version")

nfpms:
  - id: packages
    package_name: grin
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Yoshi325
    homepage: "https://github.com/Yoshi325/grin"
    maintainer: "Charles Y."
    description: "Make INI files greppable"
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: ./doc/grin.1
        dst: /usr/share/man/man1/grin.1

source:
  enabled: true
